# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  bff.web:
    build:
      context: "C:\\Users\\gwanjohi\\Documents\\Projects\\SDDemoDocker"
      dockerfile: "BFF.Web/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "bffweb:dev"
    ports:
    - "127.0.0.1:57004:57100"
    - "127.0.0.1:57204:57300"
    volumes:
    - "C:\\Users\\gwanjohi\\AppData\\Roaming\\Microsoft\\UserSecrets:/root/.microsoft/usersecrets"
    - "C:\\Users\\gwanjohi\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\gwanjohi\\Documents\\Projects\\SDDemoDocker\\BFF.Web:/app:rw"
    - "C:\\Users\\gwanjohi\\Documents\\Projects\\SDDemoDocker:/src:rw"
    - "C:\\Users\\gwanjohi\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\gwanjohi\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_8_19_09_02_48:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  locationa.api:
    build:
      context: "C:\\Users\\gwanjohi\\Documents\\Projects\\SDDemoDocker"
      dockerfile: "Locationa.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "locationaapi:dev"
    ports:
    - "127.0.0.1:57005:57100"
    - "127.0.0.1:57205:57300"
    volumes:
    - "C:\\Users\\gwanjohi\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\gwanjohi\\Documents\\Projects\\SDDemoDocker\\LocationA.API:/app:rw"
    - "C:\\Users\\gwanjohi\\Documents\\Projects\\SDDemoDocker:/src:rw"
    - "C:\\Users\\gwanjohi\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\gwanjohi\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_8_19_09_02_48:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  locationb.api:
    build:
      context: "C:\\Users\\gwanjohi\\Documents\\Projects\\SDDemoDocker"
      dockerfile: "LocationB.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "locationbapi:dev"
    ports:
    - "127.0.0.1:57006:57100"
    - "127.0.0.1:57206:57300"
    volumes:
    - "C:\\Users\\gwanjohi\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\gwanjohi\\Documents\\Projects\\SDDemoDocker\\LocationB.API:/app:rw"
    - "C:\\Users\\gwanjohi\\Documents\\Projects\\SDDemoDocker:/src:rw"
    - "C:\\Users\\gwanjohi\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\gwanjohi\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_8_19_09_02_48:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  locationc.api:
    build:
      context: "C:\\Users\\gwanjohi\\Documents\\Projects\\SDDemoDocker"
      dockerfile: "LocationC.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "locationcapi:dev"
    ports:
    - "127.0.0.1:57007:57100"
    - "127.0.0.1:57207:57300"
    volumes:
    - "C:\\Users\\gwanjohi\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\gwanjohi\\Documents\\Projects\\SDDemoDocker\\LocationC.API:/app:rw"
    - "C:\\Users\\gwanjohi\\Documents\\Projects\\SDDemoDocker:/src:rw"
    - "C:\\Users\\gwanjohi\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\gwanjohi\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_8_19_09_02_48:/var/opt/rider-debugger:rw"
    working_dir: "/app"
